# Generated by Django 5.1.1 on 2024-09-20 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='current job department')),
                ('job_role', models.CharField(choices=[('intern', 'Intern'), ('employee', 'Employee'), ('lead', 'Lead'), ('manager', 'Manager'), ('chief_officer', 'Chief Officer')], max_length=50, verbose_name='current job department')),
                ('immediate_manager', models.CharField(max_length=50, verbose_name='current job department')),
                ('working_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('on_notice_period', 'On Notice Period'), ('terminated', 'Terminated')], max_length=50, verbose_name='current job department')),
                ('hire_date', models.CharField(max_length=50, verbose_name='current job department')),
                ('reason_for_resign', models.CharField(max_length=50, verbose_name='current job department')),
                ('pancard_number', models.CharField(max_length=50, verbose_name='identification number for eg. pancard no.')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
